const langs = [
  "English (Hongkong)",
  "English (India)",
  "English (Ireland)",
  "English (New Zealand)",
  "English (Philippines)",
  "English (Singapore)",
  "English (South Africa)",
  "English (US)",
  "Arabic (Egypt)",
  "Arabic (Saudi Arabia)",
  "Bulgarian",
  "Ukraine",
  "Turkish",
  "Thai (Thailand)",
  "Tamil",
  "Sverige",
  "Spanish US",
  "Spanish Spain",
  "Spanish Mexican",
  "Spanish Latin",
  "Spanish Colombian",
  "Spanish Castilian",
  "Spanish Argentinian",
  "Slovenian",
  "Slovak",
  "Russian",
  "Romanian",
  "Portuguese (Portugal)",
  "Portuguese (Brazil)",
  "Polish",
  "Norwegian",
  "Malay",
  "Lithuanian",
  "Latvian",
  "Korean",
  "Japanese",
  "Italian",
  "Indonesia",
  "Hungarian",
  "Hindi",
  "Hebrew",
  "Greek",
  "French (Switzerland)",
  "French (France)",
  "French (Canada)",
  "French (Belgium)",
  "Finnish",
  "Estonian",
  "English (Great Britain)",
  "English (Canada)",
  "English (Australia)",
  "Dutch (Netherlands)",
  "Dutch (Belgium)",
  "Deutsch (Switzerland)",
  "Deutsch (Germany)",
  "Deutsch (Austria)",
  "Deutsch",
  "Danish",
  "Czech",
  "Croatian",
  "Chinese (Taiwanese Mandarin)",
  "Chinese (Mandarin simplified)",
  "Chinese (Cantonese tranditional)",
  "Catalan (Spanish)",
  "Arabic (Classic)",
];
export default langs;
